user: git
group: git
before_precompile: ./bin/pkgr_before_precompile.sh
targets:
  debian-7: &wheezy
    build_dependencies:
      - libicu-dev
      - cmake
      - pkg-config
    dependencies:
      - libicu48
      - libpcre3
      - git
  ubuntu-12.04: *wheezy
  ubuntu-14.04:
    build_dependencies:
      - libicu-dev
      - cmake
      - pkg-config
      - libkrb5-dev
    dependencies:
      - libicu52
      - libpcre3
      - git
  centos-6:
    build_dependencies:
      - libicu-devel
      - cmake
      - pkgconfig
    dependencies:
      - libicu
      - pcre
      - git
